/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 c.glb --transform 
Files: c.glb [13MB] > c-transformed.glb [1.5MB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/c-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fPaint_Geo_lodA_Paint_Geo_lodA_Ford_MustangShelbyGT500Rewa.geometry} material={materials.PaletteMaterial001} position={[0, 0.054, 0]} rotation={[0.001, 0, 0]} scale={0.374} />
      <group position={[0, 0.054, 0]} rotation={[0.001, 0, 0]} scale={0.374}>
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward.geometry} material={materials.cCalliperBadge_Front_LSG1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_2.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Carbon1_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_3.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019_Wheel1A_3D_3_d9d615} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_4.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_5.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019BadgeA_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_6.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_7.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Carbon1M_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_8.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Coloured_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_9.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019EngineA_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_10.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Grille1A_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_11.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Grille2A_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_12.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Grille3A_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_13.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Grille4A_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_14.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Grille5A_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_15.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019Grille6A_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_16.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019InteriorA_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_17.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019LightA_Material1} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_18.geometry} material={materials.fFord_MustangShelbyGT500RewardRecycled_2019ManufacturerP_1dce74} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_19.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.fWindow_Geo_lodA_Window_Geo_lodA_Ford_MustangShelbyGT500Reward_20.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/c-transformed.glb')
