/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pug.geometry} material={materials.yellow} />
    </group>
  )
}

useGLTF.preload('/model2.glb')
